version: '3.4'

networks:
  health:
    driver: bridge

services:
  mongo:
    image: mongo:4.2
    networks:
      - health
    environment:
      MONGOLAB_URI: ${DATABASE_URL:-}
    ports:
      - "27017:27017"