version: '3.4'

networks:
  health:
    driver: bridge

services:
  mongo:
    image: mongo:4.2
    networks:
      - health
    environment:
      MONGOLAB_URI: ${DATABASE_URL:-}
    ports:
      - "27017:27017"

  app:
    image: node:16.13.2
    volumes:
      - '.:/app/'
    working_dir: /app/
    depends_on:
      - mongo
    networks:
      - health
    env_file:
      - .env
    ports:
      - 3000:3000
    command: npm run start:dev